### ISSUE TITLE
Element items have no additional way of being added to the container aside from the constructor

### ISSUE THREAD

**Issue by gpnoel** [FullScreenShenanigans/ItemsHoldr#18]
The only time items get added to the container is when they are passed into the ItemsHoldr constructer. `addItem` has no functionality to add elements to `container`, so when `clear` is called, the items that were in the container do not get added back. This functionality should either be added in `addItem` or in `clear` if items should not be added to the container from `addItem`.

**Comment by JoshuaKGoldberg** [comment]
Removed the HTML container altogether!
